# Generated by Django 4.1.2 on 2022-10-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_theme', models.CharField(blank=True, max_length=50, null=True)),
                ('s_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'theme',
                'managed': False,
            },
        ),
    ]
