# Generated by Django 4.1.2 on 2022-10-26 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockdb'),
        ('stock', '0003_stockdb_delete_theme'),
    ]

    operations = [
    ]
