# Generated by Django 4.1.2 on 2022-10-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_merge_0003_stockdb_0003_stockdb_delete_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Div',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_ticker', models.CharField(blank=True, max_length=255, null=True)),
                ('div', models.CharField(blank=True, db_column='DIV', max_length=255, null=True)),
                ('dividend_yield', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'div',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_theme', models.CharField(blank=True, max_length=50, null=True)),
                ('s_name', models.CharField(blank=True, max_length=50, null=True)),
                ('c_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'theme',
                'managed': False,
            },
        ),
    ]
