# Generated by Django 4.1.2 on 2022-10-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_div_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_ticker', models.CharField(blank=True, max_length=255, null=True)),
                ('div', models.CharField(blank=True, db_column='DIV', max_length=255, null=True)),
                ('dividend_yield', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_div',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_ticker', models.CharField(max_length=50)),
                ('s_name', models.CharField(max_length=255)),
                ('s_date', models.DateField()),
                ('open', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('close', models.IntegerField()),
                ('s_volume', models.IntegerField()),
            ],
            options={
                'db_table': 'stock_new',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockPred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_date', models.DateTimeField(blank=True, null=True)),
                ('s_ticker', models.IntegerField(blank=True, null=True)),
                ('s_name', models.CharField(blank=True, max_length=50, null=True)),
                ('predict', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_pred',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Div',
        ),
    ]
