# Generated by Django 4.1.2 on 2022-10-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.IntegerField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.IntegerField()),
                ("is_active", models.IntegerField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={"db_table": "auth_user", "managed": False,},
        ),
        migrations.CreateModel(
            name="Mystock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={"db_table": "mystock", "managed": False,},
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "s_ticker",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("s_name", models.CharField(max_length=50)),
                ("s_kospi_section", models.CharField(max_length=50)),
            ],
            options={"db_table": "stock", "managed": False,},
        ),
    ]
