# Generated by Django 4.1.2 on 2022-10-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_div_stocknew_stockpred_delete_stockhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_ticker', models.CharField(blank=True, max_length=255, null=True)),
                ('div', models.CharField(blank=True, db_column='DIV', max_length=255, null=True)),
                ('dividend_yield', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_div',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Div',
        ),
    ]
