# Generated by Django 4.1.2 on 2022-10-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "news_url",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("news_date", models.DateField(blank=True, null=True)),
                ("news_title", models.CharField(max_length=255)),
                ("news_sum_1", models.CharField(max_length=255)),
                ("news_sum_2", models.CharField(max_length=255)),
                ("news_sum_3", models.CharField(max_length=255)),
                ("news_src", models.CharField(max_length=255)),
                ("news_rep", models.CharField(max_length=255)),
            ],
            options={"db_table": "news", "managed": False,},
        ),
    ]
