# Generated by Django 4.1.2 on 2022-10-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_date', models.DateField(blank=True, null=True)),
                ('news_title', models.CharField(max_length=255)),
                ('news_url', models.CharField(max_length=255)),
                ('news_sum_1', models.CharField(max_length=255)),
                ('news_sum_2', models.CharField(max_length=255)),
                ('news_sum_3', models.CharField(max_length=255)),
                ('news_src', models.CharField(max_length=255)),
                ('news_rep', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
    ]
