# Generated by Django 4.1.2 on 2022-10-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ant_info",
            fields=[
                (
                    "ant_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("shop_1", models.CharField(max_length=30)),
                ("shop_2", models.CharField(max_length=30)),
                ("shop_3", models.CharField(max_length=30)),
                ("shop_4", models.CharField(max_length=30)),
                ("shop_5", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="ant_stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ant_id", models.CharField(max_length=100)),
                ("stock_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="stock_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("prev_price", models.IntegerField()),
                ("up", models.BooleanField()),
            ],
        ),
    ]
